name:                demo-kubernetes-minikube
version:             0.1.0.0
license:             BSD3

dependencies:
- base
- bytestring
- monad-logger
- network
- relude
- sandwich
- sandwich-contexts
- sandwich-contexts-kubernetes
- string-interpolate
- text
- time
- unliftio

default-extensions:
- OverloadedStrings
- QuasiQuotes
- NamedFieldPuns
- RecordWildCards
- ScopedTypeVariables
- FlexibleContexts
- FlexibleInstances
- LambdaCase

ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N

executables:
  demo-kubernetes-minikube:
    main: Main.hs
    source-dirs: app
