name:                demo-minio
version:             0.1.0.0
license:             BSD3

dependencies:
- base
- bytestring
- monad-logger
- network
- sandwich
- sandwich-contexts
- sandwich-contexts-minio
- string-interpolate
- text
- unliftio

default-extensions:
- OverloadedStrings
- QuasiQuotes
- NamedFieldPuns
- RecordWildCards
- ScopedTypeVariables
- FlexibleContexts
- FlexibleInstances
- LambdaCase

ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N

executables:
  demo-minio:
    main: Main.hs
    source-dirs: app
