- arguments: [--color, --cpp-simple, -XQuasiQuotes, -j]

- ignore: {name: "Redundant bracket"}
- ignore: {name: "Redundant multi-way if"}
- ignore: {name: "Use <$>"}
- ignore: {name: "Use if"}
- ignore: {name: "Use void"}
