
resolver: nightly-2026-04-19

nix:
  enable: false

system-ghc: true

packages:
- ./sandwich
- ./sandwich-contexts
- ./sandwich-contexts-docker
- ./sandwich-contexts-kubernetes
- ./sandwich-contexts-minio
- ./sandwich-hedgehog
- ./sandwich-quickcheck
- ./sandwich-slack
- ./sandwich-webdriver

- ./sandwich-demos

- ./demos/demo-basic
- ./demos/demo-command-line-args
- ./demos/demo-context-dependencies
- ./demos/demo-context-nested
- ./demos/demo-contexts
- ./demos/demo-custom-exceptions
- ./demos/demo-discover
# - ./demos/demo-fake-smtp-server
- ./demos/demo-files
- ./demos/demo-golden
- ./demos/demo-hedgehog
- ./demos/demo-kubernetes-instrumentation
- ./demos/demo-kubernetes-kata
- ./demos/demo-kubernetes-kind
- ./demos/demo-kubernetes-longhorn
- ./demos/demo-kubernetes-minikube
- ./demos/demo-kubernetes-postgres
- ./demos/demo-kubernetes-seaweedfs
- ./demos/demo-kubernetes-typesense
- ./demos/demo-landing
- ./demos/demo-minio
- ./demos/demo-nix
- ./demos/demo-nix-binary
- ./demos/demo-nix-derivation
- ./demos/demo-paralleln
- ./demos/demo-mysql
- ./demos/demo-postgres
- ./demos/demo-processes
- ./demos/demo-quickcheck
- ./demos/demo-setup-teardown
- ./demos/demo-slack
- ./demos/demo-stack-test
- ./demos/demo-stress
- ./demos/demo-timing
- ./demos/demo-timing-parallel
- ./demos/demo-tui
- ./demos/demo-webdriver-landing
- ./demos/demo-webdriver-nix
- ./demos/demo-webdriver-normal
- ./demos/demo-webdriver-pool
- ./demos/demo-webdriver-positioning
- ./demos/demo-webdriver-video

extra-deps:
# For sandwich-contexts

- git: https://github.com/codedownio/minio-hs
  # codedown-nov-2025 branch
  commit: ebfff2c38c75b206a229aa8b9ec301f35c78dc8a

# For sandwich-contexts-docker

- git: https://github.com/codedownio/docker-engine.git
  commit: 58535cd46712dff421f2148e438c49c2700ea20e
  subdirs:
  - v1.44

# For sandwich-contexts-kubernetes

- kubernetes-api-130.0.0
- kubernetes-api-client-0.6.1.2

- git: https://github.com/krdlab/haskell-oidc-client
  commit: 2d19db09bf13f02f49248f7b21703b2c59e06ecc
