
resolver: lts-23.7

nix:
  pure: false
  packages:
  - pcre
  - pkg-config
  - postgresql
  - zlib

packages:
- ./sandwich
- ./sandwich-contexts
- ./sandwich-contexts-docker
- ./sandwich-contexts-kubernetes
- ./sandwich-contexts-minio
- ./sandwich-hedgehog
- ./sandwich-quickcheck
- ./sandwich-slack
- ./sandwich-webdriver

- ./sandwich-demos

- ./demos/demo-basic
- ./demos/demo-command-line-args
- ./demos/demo-context-dependencies
- ./demos/demo-context-nested
- ./demos/demo-contexts
- ./demos/demo-custom-exceptions
- ./demos/demo-discover
# - ./demos/demo-fake-smtp-server
- ./demos/demo-files
- ./demos/demo-golden
- ./demos/demo-hedgehog
- ./demos/demo-kubernetes-kata
- ./demos/demo-kubernetes-kind
- ./demos/demo-kubernetes-longhorn
- ./demos/demo-kubernetes-minikube
- ./demos/demo-kubernetes-seaweedfs
- ./demos/demo-landing
- ./demos/demo-minio
- ./demos/demo-nix
- ./demos/demo-nix-binary
- ./demos/demo-nix-derivation
- ./demos/demo-paralleln
- ./demos/demo-postgres
- ./demos/demo-processes
- ./demos/demo-quickcheck
- ./demos/demo-setup-teardown
- ./demos/demo-slack
- ./demos/demo-stack-test
- ./demos/demo-timing
- ./demos/demo-timing-parallel
- ./demos/demo-tui
- ./demos/demo-webdriver-landing
- ./demos/demo-webdriver-nix
- ./demos/demo-webdriver-normal
- ./demos/demo-webdriver-pool
- ./demos/demo-webdriver-positioning
- ./demos/demo-webdriver-video

extra-deps:
## For sandwich-contexts

- git: https://github.com/codedownio/minio-hs
  commit: 1e63a0ec44fff374799b25a0a02c041eab664c4f

## For sandwich-contexts-docker

- git: https://github.com/codedownio/docker-engine.git
  commit: ba5ebd823ed843a556cd8c24a5a0086a3f6e5a6c
  subdirs:
  - v1.44

## For sandwich-contexts-kubernetes

- kubernetes-api-130.0.0
- kubernetes-api-client-0.6.0.0

- git: https://github.com/codedownio/haskell-oidc-client
  # codedown-jun-2024-ghc98
  commit: b70757b85751525cba41316ea9af132d9a43cfaf

# https://github.com/kubernetes-client/haskell/issues/64
# https://github.com/channable/vaultenv/issues/99
- git: https://github.com/codedownio/hs-certificate
  # codedown-feb-2024
  # This branch
  # 1. Takes akshaymankar's fixes from https://github.com/haskell-tls/hs-certificate/pull/113
  # and rebases them on the most recent https://github.com/haskell-tls/hs-certificate master branch
  # 2. Cherry-picks kazuyamamoto's commit switching the package tocrypton, from here:
  # https://github.com/kazu-yamamoto/crypton-certificate/commit/c11bbbeec2360ce797c5eb3bd4953cbc5bf1a0d6
  commit: dcd0d5b200e96e90c6daa728585c23be5309a955
  subdirs:
  - x509-validation

## For demos

- HaskellNet-0.6.1.2@sha256:a880046501c8b035002ac2dbf597e6d416552bd04b499719997a67407602afc8,2583
