
resolver: nightly-2025-09-06

nix:
  enable: false

system-ghc: true

packages:
- ./sandwich
- ./sandwich-contexts
- ./sandwich-contexts-docker
- ./sandwich-contexts-kubernetes
- ./sandwich-contexts-minio
- ./sandwich-hedgehog
- ./sandwich-quickcheck
- ./sandwich-slack
- ./sandwich-webdriver

- ./sandwich-demos

- ./demos/demo-basic
- ./demos/demo-command-line-args
- ./demos/demo-context-dependencies
- ./demos/demo-context-nested
- ./demos/demo-contexts
- ./demos/demo-custom-exceptions
- ./demos/demo-discover
# - ./demos/demo-fake-smtp-server
- ./demos/demo-files
- ./demos/demo-golden
- ./demos/demo-hedgehog
- ./demos/demo-kubernetes-kata
- ./demos/demo-kubernetes-kind
- ./demos/demo-kubernetes-longhorn
- ./demos/demo-kubernetes-minikube
- ./demos/demo-kubernetes-seaweedfs
- ./demos/demo-landing
- ./demos/demo-minio
- ./demos/demo-nix
- ./demos/demo-nix-binary
- ./demos/demo-nix-derivation
- ./demos/demo-paralleln
- ./demos/demo-postgres
- ./demos/demo-processes
- ./demos/demo-quickcheck
- ./demos/demo-setup-teardown
- ./demos/demo-slack
- ./demos/demo-stack-test
- ./demos/demo-timing
- ./demos/demo-timing-parallel
- ./demos/demo-tui
- ./demos/demo-webdriver-landing
- ./demos/demo-webdriver-nix
- ./demos/demo-webdriver-normal
- ./demos/demo-webdriver-pool
- ./demos/demo-webdriver-positioning
- ./demos/demo-webdriver-video

extra-deps:
# For sandwich-webdriver

- webdriver-0.13.0.0

# For sandwich-contexts

- git: https://github.com/minio/minio-hs
  commit: 3e665784228cba7261560c104b8f1d928e7b5bd4

# For sandwich-contexts-docker

- git: https://github.com/codedownio/docker-engine.git
  commit: 58535cd46712dff421f2148e438c49c2700ea20e
  subdirs:
  - v1.44

# For sandwich-contexts-kubernetes

- kubernetes-api-130.0.0
- kubernetes-api-client-0.6.1.1

- git: https://github.com/krdlab/haskell-oidc-client
  commit: 2d19db09bf13f02f49248f7b21703b2c59e06ecc

# For demos

- HaskellNet-0.6.2

- cryptonite-0.30@sha256:12c85dea7be63e5ad90bcb487eb3846bf3c413347f94336fa1dede7b28f9936a,18301
- cryptonite-conduit-0.2.2@sha256:bfbae677a44f3a5cf3bf7f36271682979a402825f3d1e8767cfd62f2ddb702c2,1984
