
resolver: lts-22.27

# ghc-options:
#   "$locals": >-
#     -fwrite-ide-info
#     -hiedir .hie
#     -dumpdir .ghcdump
#     -Wredundant-constraints

nix:
  pure: false
  packages:
  - pcre
  - pkg-config
  - zlib

packages:
- ./sandwich
- ./sandwich-contexts
- ./sandwich-contexts-docker
- ./sandwich-contexts-kubernetes
- ./sandwich-contexts-minio
- ./sandwich-hedgehog
- ./sandwich-quickcheck
- ./sandwich-slack
- ./sandwich-webdriver

- ./sandwich-demos

- ./demos/demo-basic
- ./demos/demo-command-line-args
- ./demos/demo-context-dependencies
- ./demos/demo-context-nested
- ./demos/demo-contexts
- ./demos/demo-custom-exceptions
- ./demos/demo-discover
- ./demos/demo-fake-smtp-server
- ./demos/demo-golden
- ./demos/demo-hedgehog
- ./demos/demo-kubernetes-kata
- ./demos/demo-kubernetes-kind
- ./demos/demo-kubernetes-longhorn
- ./demos/demo-kubernetes-minikube
- ./demos/demo-kubernetes-seaweedfs
- ./demos/demo-landing
- ./demos/demo-minio
- ./demos/demo-nix
- ./demos/demo-nix-binary
- ./demos/demo-paralleln
- ./demos/demo-postgres
- ./demos/demo-processes
- ./demos/demo-quickcheck
- ./demos/demo-setup-teardown
- ./demos/demo-slack
- ./demos/demo-stack-test
- ./demos/demo-timing
- ./demos/demo-timing-parallel
- ./demos/demo-tui
- ./demos/demo-webdriver-landing
- ./demos/demo-webdriver-nix
- ./demos/demo-webdriver-normal
- ./demos/demo-webdriver-pool
- ./demos/demo-webdriver-positioning
- ./demos/demo-webdriver-video

extra-deps:
- vty-windows-0.2.0.0

## For sandwich-contexts

- git: https://github.com/codedownio/minio-hs
  # branch: codedown-jul-2024-tolerant
  commit: 2fae6ae212a346acf400847d0b6cc647045822d1

## For sandwich-contexts-docker

- git: https://github.com/codedownio/docker-engine.git
  commit: ba5ebd823ed843a556cd8c24a5a0086a3f6e5a6c
  subdirs:
  - v1.44

## For sandwich-contexts-kubernetes

- git: https://github.com/codedownio/kubernetes-client-haskell.git
  # codedown-feb-2024
  commit: a747f6fdc62d34c684709740422497d3c088f8d9
  subdirs:
  - kubernetes-1.27
  - kubernetes-client

- git: https://github.com/codedownio/haskell-oidc-client
  # codedown-jan-2024-ghc96
  commit: 4c122412e80c45bd28d03ead16f1a153bd53fcf4

# https://github.com/kubernetes-client/haskell/issues/64
# https://github.com/channable/vaultenv/issues/99
- git: https://github.com/codedownio/hs-certificate
  # codedown-feb-2024
  # This branch
  # 1. Takes akshaymankar's fixes from https://github.com/haskell-tls/hs-certificate/pull/113
  # and rebases them on the most recent https://github.com/haskell-tls/hs-certificate master branch
  # 2. Cherry-picks kazuyamamoto's commit switching the package tocrypton, from here:
  # https://github.com/kazu-yamamoto/crypton-certificate/commit/c11bbbeec2360ce797c5eb3bd4953cbc5bf1a0d6
  commit: dcd0d5b200e96e90c6daa728585c23be5309a955
  subdirs:
  - x509-validation
