
resolver: nightly-2025-04-24
compiler: ghc-9.12.2

nix:
  pure: false
  packages:
  - pcre
  - pkg-config
  - postgresql
  - zlib

packages:
- ./sandwich
- ./sandwich-contexts
- ./sandwich-contexts-docker
- ./sandwich-contexts-kubernetes
- ./sandwich-contexts-minio
- ./sandwich-hedgehog
- ./sandwich-quickcheck
- ./sandwich-slack
- ./sandwich-webdriver

- ./sandwich-demos

- ./demos/demo-basic
- ./demos/demo-command-line-args
- ./demos/demo-context-dependencies
- ./demos/demo-context-nested
- ./demos/demo-contexts
- ./demos/demo-custom-exceptions
- ./demos/demo-discover
# - ./demos/demo-fake-smtp-server
- ./demos/demo-files
- ./demos/demo-golden
- ./demos/demo-hedgehog
- ./demos/demo-kubernetes-kata
- ./demos/demo-kubernetes-kind
- ./demos/demo-kubernetes-longhorn
- ./demos/demo-kubernetes-minikube
- ./demos/demo-kubernetes-seaweedfs
- ./demos/demo-landing
- ./demos/demo-minio
- ./demos/demo-nix
- ./demos/demo-nix-binary
- ./demos/demo-nix-derivation
- ./demos/demo-paralleln
- ./demos/demo-postgres
- ./demos/demo-processes
- ./demos/demo-quickcheck
- ./demos/demo-setup-teardown
- ./demos/demo-slack
- ./demos/demo-stack-test
- ./demos/demo-timing
- ./demos/demo-timing-parallel
- ./demos/demo-tui
- ./demos/demo-webdriver-landing
- ./demos/demo-webdriver-nix
- ./demos/demo-webdriver-normal
- ./demos/demo-webdriver-pool
- ./demos/demo-webdriver-positioning
- ./demos/demo-webdriver-video

extra-deps:
## For sandwich-contexts

- git: https://github.com/minio/minio-hs
  commit: 3e665784228cba7261560c104b8f1d928e7b5bd4

## For sandwich-contexts-docker

- git: https://github.com/codedownio/docker-engine.git
  commit: 58535cd46712dff421f2148e438c49c2700ea20e
  subdirs:
  - v1.44

## For sandwich-contexts-kubernetes

- git: https://github.com/codedownio/kubernetes-api.git
  commit: 40a7f4361de2fd8f23630de1955c615421c38d66
  subdirs:
  - kubernetes-api-1.30
  - kubernetes-api-client
# - kubernetes-api-130.0.0
# - kubernetes-api-client-0.6.0.1

- git: https://github.com/krdlab/haskell-oidc-client
  commit: 2d19db09bf13f02f49248f7b21703b2c59e06ecc

## For demos

- HaskellNet-0.6.2
