name: sandwich-contexts
version: 0.3.0.2
synopsis: Contexts for the Sandwich test library
license: BSD3
description: Please see the <https://codedownio.github.io/sandwich documentation>.
author: Tom McLaughlin
maintainer: tom@codedown.io
copyright: 2024 Tom McLaughlin

extra-source-files:
- CHANGELOG.md

dependencies:
- base >= 4.11 && < 5
- sandwich >= 0.3.0.0
- unliftio

default-extensions:
- OverloadedStrings
- QuasiQuotes
- NamedFieldPuns
- RecordWildCards
- ScopedTypeVariables
- LambdaCase
- MultiWayIf
- ViewPatterns
- TupleSections
- FlexibleContexts
- NoImplicitPrelude
- NumericUnderscores

ghc-options:
- -Wunused-packages # For GHC 8.10.1 and above
- -Wall
# - -Wpartial-fields
# - -Wredundant-constraints # Reports HasCallStack, so keep it off normally

library:
  source-dirs: lib
  exposed-modules:
  - Test.Sandwich.Contexts.Container
  - Test.Sandwich.Contexts.FakeSmtpServer
  - Test.Sandwich.Contexts.Files
  - Test.Sandwich.Contexts.HttpWaits
  - Test.Sandwich.Contexts.Nix
  - Test.Sandwich.Contexts.PostgreSQL
  - Test.Sandwich.Contexts.Types.Network
  - Test.Sandwich.Contexts.Types.S3
  - Test.Sandwich.Contexts.Util.Ports
  dependencies:
  - aeson
  - conduit
  - conduit-extra >= 1.3.7 # For Unix socket support on Windows
  - containers
  - exceptions
  - filepath
  - http-client
  - http-conduit
  - http-types
  - HTTP
  - monad-logger
  - mtl
  - network
  - process
  - random
  - relude
  - retry
  - safe
  - streaming-commons >= 0.2.3.0 # For Unix socket support on Windows
  - string-interpolate
  - temporary
  - text
  - time
  - transformers
  - unix-compat
  - unliftio-core
  - vector
  when:
  - condition: "impl(ghc >= 9.6)"
    dependencies:
    - crypton-connection
    - data-default
  - condition: "impl(ghc < 9.6)"
    dependencies:
    - connection

tests:
  tests:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -Wall
    - -rtsopts
    - -threaded
    dependencies:
    - filepath
    - postgresql-simple
    - relude
    - sandwich-contexts
    - string-interpolate
    build-tools: sandwich:sandwich-discover
