name:                sandwich-slack
version:             0.1.2.0
github:              "codedownio/sandwich"
license:             BSD3
author:              "Tom McLaughlin"
maintainer:          "tom@codedown.io"
copyright:           "2023 Tom McLaughlin"
category:            Testing
homepage:            https://codedownio.github.io/sandwich
synopsis:            Sandwich integration with Slack
description:         Please see the <https://codedownio.github.io/sandwich/docs/extensions/sandwich-slack documentation>.

extra-source-files:
- CHANGELOG.md

dependencies:
- aeson
- base < 5
- bytestring
- containers
- lens
- lens-aeson
- monad-logger
- mtl
- safe
- safe-exceptions
- sandwich
- stm
- string-interpolate
- text
- time
- vector
- wreq

default-extensions:
- FlexibleContexts
- FlexibleInstances
- LambdaCase
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- QuasiQuotes
- RecordWildCards
- ScopedTypeVariables
- ViewPatterns

library:
  source-dirs: src
  ghc-options:
  - -W
  exposed-modules:
  - Test.Sandwich.Formatters.Slack
  - Test.Sandwich.Formatters.Slack.Internal

executables:
  sandwich-slack-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sandwich-slack

tests:
  sandwich-slack-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
