name:                demo-nix-derivation
version:             0.1.0.0
license:             BSD3

dependencies:
- base
- monad-logger
- mtl
- sandwich
- sandwich-contexts
- string-interpolate
- unliftio

default-extensions:
- OverloadedStrings
- QuasiQuotes
- NamedFieldPuns
- RecordWildCards
- ScopedTypeVariables
- FlexibleContexts
- FlexibleInstances
- LambdaCase

ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N

executables:
  demo-nix-derivation:
    main: Main.hs
    source-dirs: app
