name:                sandwich
version:             0.3.0.3
github:              "codedownio/sandwich"
license:             BSD3
author:              "Tom McLaughlin"
maintainer:          "tom@codedown.io"
copyright:           "2024 Tom McLaughlin"
category:            Testing
homepage:            https://codedownio.github.io/sandwich
synopsis:            Yet another test framework for Haskell
description:         Please see the <https://codedownio.github.io/sandwich documentation>.

extra-source-files:
- CHANGELOG.md

default-extensions:
- FlexibleContexts
- FlexibleInstances
- LambdaCase
- NamedFieldPuns
- NumericUnderscores
- OverloadedStrings
- QuasiQuotes
- RecordWildCards
- ScopedTypeVariables
- ViewPatterns

dependencies:
- aeson
- ansi-terminal
- async
- base >= 4.11 && < 5
- brick
- colour
- containers
- bytestring
- deepseq
- directory
- exceptions
- filepath
- free
- microlens
- microlens-th
- monad-control
- monad-logger
- mtl
- optparse-applicative
- pretty-show
- process
- retry
- safe
- stm
- string-interpolate
- text
- time
- transformers
- transformers-base
- unliftio
- unliftio-core
- vector
- vty >= 6
- vty-crossplatform

# For spec discovery. Move to its own package?
- template-haskell
- haskell-src-exts

when:
- condition: "!os(windows)"
  dependencies:
  - unix

library:
  source-dirs: src
  ghc-options:
  - -Wall
  exposed-modules:
  - Test.Sandwich
  - Test.Sandwich.Contexts
  - Test.Sandwich.Expectations
  - Test.Sandwich.Golden
  - Test.Sandwich.Logging
  - Test.Sandwich.Misc
  - Test.Sandwich.Nodes
  - Test.Sandwich.Options
  - Test.Sandwich.Formatters.FailureReport
  - Test.Sandwich.Formatters.LogSaver
  - Test.Sandwich.Formatters.Print
  - Test.Sandwich.Formatters.Silent
  - Test.Sandwich.Formatters.TerminalUI
  - Test.Sandwich.Internal
  - Test.Sandwich.TH
  - Test.Sandwich.Util.Process
  - Test.Sandwich.Waits
  when:
  - condition: "os(windows)"
    dependencies:
    - Win32

executables:
  sandwich-demo:
    main: Main.hs
    source-dirs:
    - app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sandwich

  sandwich-discover:
    main: Main.hs
    source-dirs:
    - discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sandwich

  sandwich-test:
    main: Main.hs
    source-dirs:
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sandwich

tests:
  sandwich-test-suite:
    main: Main.hs
    source-dirs:
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sandwich
