#!/usr/bin/env bash

stack build

stack build --stack-yaml stack/stack-9.2.8.yaml
stack build --stack-yaml stack/stack-9.4.8.yaml
stack build --stack-yaml stack/stack-9.6.7.yaml
stack build --stack-yaml stack/stack-9.8.4.yaml
stack build --stack-yaml stack/stack-9.10.2.yaml
