name:                sandwich-webdriver
version:             0.2.3.1
github:              "codedownio/sandwich"
license:             BSD3
author:              "Tom McLaughlin"
maintainer:          "tom@codedown.io"
copyright:           "2023 Tom McLaughlin"
category:            Testing
homepage:            https://codedownio.github.io/sandwich
synopsis:            Sandwich integration with Selenium WebDriver
description:         Please see the <https://codedownio.github.io/sandwich/docs/extensions/sandwich-webdriver documentation>.

extra-source-files:
- CHANGELOG.md

dependencies:
- aeson
- base < 5
- bytestring
- containers
- data-default
- directory
- exceptions
- filepath
- http-client
- http-client-tls
- http-conduit
- microlens
- microlens-aeson
- monad-control
- monad-logger
- mtl
- network
- process
- random
- retry
- safe
- sandwich >= 0.1.0.3
- string-interpolate
- text
- time
- transformers
- unliftio
- unliftio-core
- unordered-containers
- vector
- webdriver

default-extensions:
- FlexibleContexts
- FlexibleInstances
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NumericUnderscores
- OverloadedStrings
- QuasiQuotes
- RecordWildCards
- ScopedTypeVariables
- ViewPatterns

library:
  source-dirs: src
  other-modules:
  - Test.Sandwich.WebDriver.Resolution
  ghc-options:
  - -W
  when:
  - condition: "!os(windows)"
    source-dirs: unix-src
    dependencies:
    - temporary
  # exposed-modules:
  #   - Test.Sandwich.Webdriver
  #   - Test.Sandwich.Webdriver.Video
  #   - Test.Sandwich.Webdriver.Windows

when:
- condition: os(darwin)
  source-dirs: darwin-src
  frameworks:
  - CoreGraphics
- condition: os(windows)
  source-dirs: windows-src
- condition: os(linux)
  source-dirs: linux-src
  dependencies:
  - regex-compat
- condition: "!os(windows)"
  dependencies:
  - unix

executables:
  sandwich-webdriver-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sandwich-webdriver
    - time

tests:
  sandwich-webdriver-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sandwich-webdriver
    - unliftio
