name:                sandwich-webdriver
version:             0.4.0.1
github:              "codedownio/sandwich"
license:             BSD3
author:              "Tom McLaughlin"
maintainer:          "tom@codedown.io"
copyright:           "2025 Tom McLaughlin"
category:            Testing
homepage:            https://codedownio.github.io/sandwich
synopsis:            Sandwich integration with Selenium WebDriver
description:         Please see the <https://codedownio.github.io/sandwich/docs/extensions/sandwich-webdriver documentation>.

extra-source-files:
- CHANGELOG.md

dependencies:
- aeson
- base < 5
- bytestring
- containers
- data-default
- directory
- exceptions
- filepath
- http-client
- http-client-tls
- http-conduit
- http-types
- microlens
- microlens-aeson
- monad-control
- monad-logger
- mtl
- network
- process
- random
- retry
- safe
- sandwich >= 0.3.0.0
- sandwich-contexts >= 0.3.0.0
- string-interpolate
- temporary
- text
- time
- transformers
- unliftio
- unliftio-core
- unordered-containers
- vector
- webdriver >= 0.13.0.0

default-extensions:
- FlexibleContexts
- FlexibleInstances
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NumericUnderscores
- OverloadedStrings
- QuasiQuotes
- RecordWildCards
- ScopedTypeVariables
- ViewPatterns

library:
  source-dirs: src
  exposed-modules:
  - Test.Sandwich.WebDriver
  - Test.Sandwich.WebDriver.Binaries
  - Test.Sandwich.WebDriver.Config
  - Test.Sandwich.WebDriver.Video
  - Test.Sandwich.WebDriver.Windows
  ghc-options:
  - -W
  when:
  - condition: "!os(windows)"
    source-dirs: unix-src

when:
- condition: os(darwin)
  source-dirs: darwin-src
  frameworks:
  - CoreGraphics
- condition: os(windows)
  source-dirs: windows-src
- condition: os(linux)
  source-dirs: linux-src
  dependencies:
  - regex-tdfa
- condition: "!os(windows)"
  dependencies:
  - unix

tests:
  sandwich-webdriver-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sandwich-webdriver
    - unliftio
