name: sandwich-contexts-minio
version: 0.1.0.0
synopsis: Sandwich test contexts for MinIO
license: BSD3
description: Please see README.md
author: Tom McLaughlin
maintainer: tom@codedown.io
copyright: 2024 Tom McLaughlin
dependencies:
- base >= 4.11 && < 5
- sandwich >= 0.3.0.3
- unliftio

default-extensions:
- OverloadedStrings
- QuasiQuotes
- NamedFieldPuns
- RecordWildCards
- ScopedTypeVariables
- LambdaCase
- MultiWayIf
- ViewPatterns
- TupleSections
- FlexibleContexts
- NoImplicitPrelude
- NumericUnderscores

ghc-options:
- -Wunused-packages # For GHC 8.10.1 and above
- -Wall
# - -Wpartial-fields
# - -Wredundant-constraints # Reports HasCallStack, so keep it off normally

library:
  source-dirs: lib
  exposed-modules:
  - Test.Sandwich.Contexts.MinIO
  dependencies:
  - aeson
  - containers
  - exceptions
  - filepath
  - minio-hs
  - monad-logger
  - network
  - network-uri
  - random
  - relude
  - retry
  - safe
  - sandwich-contexts
  - string-interpolate
  - temporary
  - text
  - unliftio-core

# tests:
#   tests:
#     main: Main.hs
#     source-dirs: test
#     ghc-options:
#     - -Wall
#     - -rtsopts
#     - -threaded
#     dependencies:
#     - filepath
#     - relude
#     - sandwich-contexts
#     - string-interpolate
