name:                demo-stress
version:             0.1.0.0
license:             BSD3

dependencies:
- base
- random
- sandwich
- string-interpolate
- text

default-extensions:
- OverloadedStrings
- QuasiQuotes
- NamedFieldPuns
- RecordWildCards
- ScopedTypeVariables
- FlexibleContexts
- FlexibleInstances
- LambdaCase

ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N
- -fdistinct-constructor-tables
- -finfo-table-map
- -g

executables:
  demo-stress:
    main: Main.hs
    source-dirs: app
