name: sandwich-contexts-kubernetes
version: 0.1.1.1
synopsis: Sandwich test contexts for Kubernetes
license: BSD3
description: Please see README.md
author: Tom McLaughlin
maintainer: tom@codedown.io
copyright: 2025 Tom McLaughlin
dependencies:
- base >= 4.11 && < 5
- sandwich

default-extensions:
- OverloadedStrings
- QuasiQuotes
- NamedFieldPuns
- RecordWildCards
- ScopedTypeVariables
- LambdaCase
- MultiWayIf
- ViewPatterns
- TupleSections
- FlexibleContexts
- NoImplicitPrelude
- NumericUnderscores

ghc-options:
- -Wunused-packages
- -Wall
# - -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: lib
  exposed-modules:
  - Test.Sandwich.Contexts.Kubernetes
  - Test.Sandwich.Contexts.Kubernetes.Images
  - Test.Sandwich.Contexts.Kubernetes.KataContainers
  - Test.Sandwich.Contexts.Kubernetes.KindCluster
  - Test.Sandwich.Contexts.Kubernetes.MinikubeCluster
  - Test.Sandwich.Contexts.Kubernetes.MinioOperator
  - Test.Sandwich.Contexts.Kubernetes.MinioS3Server
  - Test.Sandwich.Contexts.Kubernetes.Namespace
  - Test.Sandwich.Contexts.Kubernetes.SeaweedFS
  dependencies:
  - sandwich-contexts
  - sandwich-contexts-minio
  - aeson
  - bytestring
  - containers
  - exceptions
  - filepath
  - http-client
  - kubernetes-api
  - kubernetes-api-client >= 0.6.1.1
  - lens
  - lens-aeson
  - minio-hs
  - monad-logger
  - network
  - network-uri
  - process
  - random
  - regex-tdfa
  - relude
  - retry
  - safe
  - string-interpolate
  - temporary
  - text
  - unliftio
  - unliftio-core
  - vector
  - yaml

tests:
  sandwich-contexts-kubernetes-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - random
    - relude
    - sandwich
    - sandwich-contexts
    - sandwich-contexts-kubernetes
    - string-interpolate
    - unliftio
    - unliftio-core
