name:                demo-landing
version:             0.1.0.0
license:             BSD3

dependencies:
- base
- random
- sandwich
- sandwich-demos

default-extensions:
- OverloadedStrings
- QuasiQuotes
- NamedFieldPuns
- RecordWildCards
- ScopedTypeVariables
- FlexibleContexts
- FlexibleInstances
- LambdaCase

ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N

executables:
  demo-landing:
    main: Main.hs
    source-dirs: app
