name:                demo-command-line-args
version:             0.1.0.0
license:             BSD3

dependencies:
- base
- optparse-applicative
- sandwich
- string-interpolate

default-extensions:
- OverloadedStrings
- QuasiQuotes
- NamedFieldPuns
- RecordWildCards
- ScopedTypeVariables
- FlexibleContexts
- FlexibleInstances
- LambdaCase

ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N

executables:
  demo-command-line-args:
    main: Main.hs
    source-dirs: app
